sudo: false
language: node_js
node_js:
- '0.12'
env:
  global:
  - secure: Swu6LINfQGhinOMtYyopRGH8zlHQed5ErI/XXk0H4J+r+Ev3bTjCpqt209dcuVnx7OsiQcLgx9NBbDRRsvyWD+NLTiEYBseMEqH97d06zzASDL7lNxCXFnd20byU+UevwdXTYqPXOf5h+BYJkzQD+mI1uA1gBr7ST4ZHl/urk5U=
  - secure: h+dMd2+btWavGeNSGWr4Cy4n3LWIyLWIchso3cjNIqVnjDS44eKqoCX0IgbQbNfYxoPgl85+vB7Fl7nKBPsZTNtnuhIzqfgRtc4veUUmidZIHJ2yOX8S/qKNWMotx2jki6nCaxqxDm5gTQD/ZiWD0a550kmifgjvJwcUiVEGyy4=
before_script:
- npm install -g gulp
- npm install -g bower
- bower install -f
script:
- gulp
after_success:
- gulp deploy
