sudo: false
language: node_js
node_js:
- '0.12'
env:
  global:
  - secure: h/OPd2ZjS+RBS9Bh1cXOVO7KOCVrIGRI5fld46XJKINyuXBjhmAbhNd+g6BnCuX1py9GoRg6XwQy0voKjrno9KKvAdDKenbz3eB4g8dGIpY41nYwZHIBnaPEmQ7hunyB7BzQSJD0AzOW9zCX1juZcWq3N7zmpMDtDG2skBgJaKY=
  - secure: X0sChLPQtqxnzudbUmbIYfw8qmpkOqZrx/BBd43faffBGXISj0Lgj98g1ff2OZ6cHKCXhKpeexqEDX28ZmNHk5e/qeyTAZmjwSM6zX83zwF+aYaR9mI3/2f6vA+k2Dak93QvQlAgbuijv/ftYm0S4lDISUWVq/aSntyhGPaKje8=
before_script:
- npm install -g gulp
- npm install -g bower
- bower install -f
script:
- gulp
after_success:
- gulp deploy
